#Puerto del servidor
server:
  port: 8080
#Directorio del banner de Springboot tras arrancar el servidor
banner:
  location: classpath:/bannerspring/banner.txt
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false  # JDBC url of the database.
    username: root                                              # Login user of the database.
    password:                                          # Login password of the database.
  jpa:
    show-sql: true                                              # Enable logging of SQL statements.
    hibernate:
      ddl-auto: update                                          # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
      naming:
        strategy: org.hibernate.cfg.improvedNamingStrategy      # Hibernate 4 naming strategy fully qualified name. Not supported with Hibernate 5.
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect              # Additional native properties to set on the JPA provider.
  
  thymeleaf:
    cache: false                                                # No admite cache en Thyleaf